services:
  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      WORKING_DIR: ${WORKING_DIR}
    volumes:
      - "${WORKING_DIR}:/var/lib/postgresql/data"
  ui:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080